USE ThriftED;

INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Lucio', 'De Moreno', '1975-10-30', 29, 'ldemoreno0@vkontakte.ru');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Rik', 'Amar', '1989-09-06', 46, 'ramar1@simplemachines.org');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Sophi', 'Blanque', '1995-06-21', 26, 'sblanque2@tinypic.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Yule', 'Youens', '1973-07-12', 58, 'yyouens3@alibaba.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Panchito', 'McCay', '1976-06-05', 40, 'pmccay4@lulu.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Conan', 'Armfirld', '1972-09-08', 47, 'carmfirld5@dion.ne.jp');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Rycca', 'Hatfull', '1972-01-25', 59, 'rhatfull6@360.cn');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Shaylah', 'Bertomieu', '1980-06-29', 57, 'sbertomieu7@businesswire.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Hyacintha', 'Solley', '1974-11-26', 36, 'hsolley8@clickbank.net');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Dalt', 'Grzes', '1989-12-22', 41, 'dgrzes9@omniture.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Gerri', 'Losebie', '1966-02-13', 26, 'glosebiea@livejournal.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Sherilyn', 'Cromett', '1981-01-01', 41, 'scromettb@shop-pro.jp');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Candice', 'Warry', '1988-08-19', 48, 'cwarryc@addtoany.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Fania', 'Enticott', '1984-03-18', 58, 'fenticottd@over-blog.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Lurleen', 'Kienzle', '1978-10-26', 36, 'lkienzlee@imageshack.us');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Udell', 'Cumber', '1973-10-28', 56, 'ucumberf@nhs.uk');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Tiffy', 'Clear', '1974-04-01', 47, 'tclearg@ow.ly');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Germayne', 'Mabbe', '1990-05-23', 56, 'gmabbeh@homestead.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Horatia', 'Hubbucke', '1997-07-11', 56, 'hhubbuckei@oakley.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Alexis', 'Gerhardt', '1975-07-21', 47, 'agerhardtj@nba.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Anissa', 'Haberjam', '1983-11-24', 50, 'ahaberjamk@japanpost.jp');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Kristan', 'Gibb', '1985-11-16', 45, 'kgibbl@stanford.edu');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Neal', 'O''Doran', '1989-09-20', 54, 'nodoranm@netscape.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Misti', 'Eyles', '1972-10-15', 59, 'meylesn@addthis.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Hansiain', 'Brickett', '1973-08-15', 57, 'hbricketto@nydailynews.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Minnaminnie', 'Lowin', '1969-05-14', 43, 'mlowinp@meetup.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Cordey', 'Elletson', '1977-08-26', 55, 'celletsonq@hugedomains.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Jordon', 'Jerome', '1969-12-14', 49, 'jjeromer@stumbleupon.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Matilde', 'Vanyashkin', '1965-05-15', 41, 'mvanyashkins@4shared.com');
INSERT INTO Analyst (FirstName, LastName, BirthDate, Age, Email) VALUES ('Regine', 'Greger', '1968-03-21', 51, 'rgregert@springer.com');