USE ThriftED;

INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (15, '2023-02-27', '94 Iowa Center', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (23, '2024-06-02', '2144 Delaware Lane', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (8, '2024-02-06', '440 Delaware Drive', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (34, '2024-03-02', '772 Graceland Center', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (12, '2024-07-22', '55 Banding Alley', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (29, '2024-05-25', '4 Bellgrove Crossing', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (7, '2023-05-16', '7 Dapin Drive', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (18, '2024-10-04', '87 Kinsman Plaza', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (5, '2023-02-05', '17 Browning Drive', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (31, '2023-11-15', '12699 Sullivan Park', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (22, '2023-05-05', '6 Bluejay Street', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (14, '2023-04-18', '32351 East Trail', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (9, '2023-10-10', '999 Huxley Drive', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (27, '2023-12-18', '964 Green Ridge Park', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (3, '2023-04-17', '12688 Claremont Way', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (36, '2024-05-18', '2959 Sunfield Point', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (11, '2023-12-08', '3177 Talisman Trail', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (19, '2023-03-27', '864 Di Loreto Center', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (25, '2024-03-05', '40489 Mendota Circle', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (2, '2023-09-30', '2 Portage Center', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (38, '2023-07-16', '63038 Victoria Center', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (16, '2023-12-06', '3 Pleasure Crossing', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (33, '2023-10-11', '475 Mccormick Pass', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (40, '2023-12-20', '953 Stuart Pass', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (6, '2024-04-21', '0 School Trail', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (21, '2024-07-23', '82 Ohio Crossing', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (13, '2024-06-07', '621 Hauk Circle', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (28, '2024-07-29', '87 Florence Center', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (17, '2023-12-18', '5001 Memorial Point', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (30, '2024-08-10', '05 Kingsford Parkway', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (4, '2024-09-13', '4224 Johnson Road', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (24, '2024-10-22', '01 Pearson Trail', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (10, '2024-02-05', '58 Little Fleur Drive', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (35, '2024-05-16', '648 Graceland Court', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (1, '2024-03-29', '6 Buena Vista Avenue', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (39, '2024-01-18', '6 Westridge Pass', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (20, '2024-02-06', '7001 Kensington Park', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (32, '2024-02-02', '7 Clyde Gallagher Way', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (26, '2024-01-15', '085 Carpenter Drive', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (37, '2024-08-05', '4298 Ruskin Drive', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (15, '2024-04-02', '13 Clyde Gallagher Pass', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (8, '2024-04-11', '7182 Tomscot Way', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (23, '2023-11-12', '97 Anderson Trail', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (12, '2024-05-10', '886 Lakeland Circle', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (34, '2023-07-05', '384 Dunning Court', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (7, '2024-09-02', '2 Kensington Avenue', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (29, '2023-09-18', '86 Anhalt Center', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (18, '2023-06-18', '61293 Heffernan Center', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (5, '2024-06-15', '998 Transport Plaza', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (31, '2023-03-15', '83806 Amoth Park', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (22, '2024-03-01', '71726 Coleman Court', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (14, '2024-09-25', '93 Manitowish Hill', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (9, '2023-03-12', '908 Briar Crest Crossing', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (27, '2024-10-31', '3 Cardinal Place', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (3, '2023-11-27', '24 Doe Crossing Hill', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (36, '2024-04-01', '265 Sachtjen Center', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (11, '2023-04-11', '2 Artisan Parkway', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (19, '2023-02-03', '231 Fieldstone Court', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (25, '2024-08-16', '5276 Southridge Lane', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (2, '2024-05-18', '892 Graceland Court', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (38, '2024-08-06', '7891 Lighthouse Bay Street', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (16, '2023-04-01', '0 Kedzie Hill', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (33, '2024-11-11', '9 Banding Crossing', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (40, '2024-07-13', '68642 Heffernan Park', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (6, '2024-05-23', '1709 Valley Edge Lane', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (21, '2024-05-28', '26340 Express Drive', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (13, '2024-06-06', '877 Eggendart Circle', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (28, '2023-10-21', '9044 Calypso Court', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (17, '2024-09-11', '4005 Petterle Place', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (30, '2023-05-13', '030 Nova Trail', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (4, '2023-12-24', '4761 Ludington Center', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (24, '2024-07-28', '362 Sachtjen Center', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (10, '2023-07-21', '19282 Main Plaza', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (35, '2023-11-28', '4092 Johnson Circle', NULL, NULL, NULL);
INSERT INTO Orders (BuyerID, OrderDate, PickupStreet, PickupCity, PickupState, PickupZip) VALUES (1, '2023-11-11', '1165 Larry Road', NULL, NULL, NULL);