USE ThriftED;

INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (5, 'vehicula condimentum curabitur in libero ut massa volutpat', 'Silbert');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (9, 'rutrum at lorem integer tincidunt ante vel', 'Oles');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (36, 'id ligula suspendisse', 'Crutchfield');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (17, 'id sapien in', 'Driutti');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (24, 'justo eu', 'Mccaull');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (37, 'volutpat convallis morbi odio odio elementum eu interdum', 'Bridger');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (29, 'etiam faucibus cursus urna ut tellus nulla ut', 'Cutridge');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (28, 'odio in hac habitasse platea dictumst maecenas ut massa', 'O'' Cloney');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (31, 'habitasse platea dictumst etiam faucibus cursus urna ut', 'Tregaskis');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (5, 'maecenas rhoncus aliquam lacus morbi', 'Guiden');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (24, 'libero quis orci nullam molestie', 'Hayfield');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (3, 'lorem vitae', 'Perton');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (22, 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque', 'Rowlings');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (23, 'et magnis dis parturient montes nascetur ridiculus mus', 'Currier');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (16, 'nulla eget eros', 'Harwin');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (29, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus', 'Tremoulet');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (37, 'sed accumsan felis ut at dolor quis odio consequat', 'Blastock');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (27, 'lorem ipsum', 'Bartalot');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (13, 'nulla tempus vivamus in felis eu sapien cursus vestibulum proin', 'Mabbett');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (2, 'id nulla ultrices aliquet maecenas leo odio condimentum id luctus', 'Trahearn');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (5, 'viverra dapibus', 'Ainley');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (19, 'sit amet', 'Creaser');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (9, 'ipsum dolor sit amet consectetuer adipiscing', 'Dono');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (18, 'amet justo', 'Syphas');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (1, 'ac lobortis vel dapibus at diam', 'Fourcade');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (28, 'amet', 'Dussy');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (3, 'in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem', 'McAline');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (19, 'sapien varius', 'Snow');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (7, 'ultrices phasellus id sapien in sapien', 'Cardenas');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (13, 'lobortis convallis tortor', 'McFadin');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (16, 'ultrices mattis odio donec vitae nisi nam ultrices', 'Keach');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (40, 'pretium quis lectus', 'Tuther');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (15, 'at', 'Maleham');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (12, 'nam dui proin leo odio porttitor id consequat', 'Denton');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (22, 'sapien iaculis congue vivamus metus arcu adipiscing', 'Manuele');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (18, 'erat fermentum justo nec', 'Calltone');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (1, 'nam dui proin leo odio porttitor id', 'Cooney');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (28, 'sem mauris laoreet ut rhoncus', 'Axon');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (23, 'massa volutpat convallis morbi odio odio elementum', 'Maton');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (36, 'adipiscing lorem', 'Lundy');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (37, 'id massa id nisl venenatis', 'Suscens');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (14, 'nisi', 'Trumble');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (21, 'luctus et ultrices', 'Swatten');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (40, 'tincidunt lacus at velit vivamus vel nulla eget eros', 'Faulo');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (25, 'enim leo rhoncus sed vestibulum sit', 'Maha');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (34, 'amet cursus id turpis integer aliquet massa id lobortis convallis', 'Brithman');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (3, 'donec semper sapien a libero nam', 'Haysey');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (35, 'rutrum ac lobortis vel', 'Abarough');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (26, 'molestie hendrerit at vulputate vitae', 'Gammack');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (2, 'pede posuere nonummy integer non', 'Ottam');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (4, 'varius ut blandit non interdum in', 'Swinburne');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (3, 'pellentesque eget nunc donec', 'Canby');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (10, 'nec molestie', 'Rankine');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (17, 'primis in', 'Benkhe');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (34, 'nisi nam ultrices libero non mattis pulvinar nulla', 'O''Luby');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (13, 'amet eleifend pede libero quis orci nullam molestie nibh in', 'Hunter');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (13, 'odio', 'Mussolini');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (40, 'faucibus orci luctus et ultrices', 'McLachlan');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (26, 'convallis nunc proin at turpis', 'Petrol');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (3, 'quis tortor id nulla ultrices aliquet', 'Atcock');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (37, 'ipsum ac tellus semper', 'Vasechkin');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (20, 'nec sem duis', 'Verner');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (30, 'lorem quisque ut erat', 'Berthod');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (14, 'fermentum donec', 'Hatzar');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (4, 'aliquet at feugiat non pretium quis lectus suspendisse potenti', 'Fleet');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (9, 'nunc donec quis orci eget orci', 'Myford');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (37, 'ac leo pellentesque ultrices mattis odio donec', 'Rawcliff');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (5, 'metus aenean fermentum donec ut mauris eget', 'Keningley');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (7, 'turpis elementum ligula vehicula consequat morbi a ipsum', 'Snalom');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (27, 'non quam nec dui', 'Pascall');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (25, 'viverra diam vitae quam suspendisse', 'Ganley');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (24, 'ante vivamus tortor duis mattis egestas metus aenean', 'Bickerstaffe');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (13, 'nullam molestie nibh in lectus', 'Hellicar');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (28, 'ultrices', 'Pedracci');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (10, 'sem praesent', 'Pickston');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (14, 'interdum in ante vestibulum ante ipsum', 'Harrowell');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (1, 'ac diam cras pellentesque volutpat dui maecenas tristique est et', 'Sambles');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (37, 'tincidunt', 'Stieger');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (14, 'leo maecenas pulvinar lobortis est phasellus sit amet', 'Jamme');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (13, 'convallis eget eleifend luctus ultricies eu', 'Scini');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (39, 'elit proin risus praesent lectus vestibulum quam sapien', 'Iacobini');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (8, 'montes nascetur ridiculus mus', 'Ragbourn');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (12, 'curae mauris viverra diam vitae quam', 'Valasek');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (40, 'nulla ultrices aliquet maecenas leo odio condimentum id', 'Bowsher');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (28, 'diam cras pellentesque volutpat dui maecenas tristique est', 'Bolton');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (8, 'viverra pede', 'Joannet');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (36, 'pede libero quis orci nullam', 'McKinnell');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (10, 'venenatis turpis enim', 'Keming');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (3, 'sit amet consectetuer adipiscing elit', 'Hugnot');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (33, 'quam', 'Macconachy');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (28, 'primis in faucibus orci luctus et ultrices posuere cubilia curae', 'Fucher');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (16, 'magnis', 'Ballinghall');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (15, 'et ultrices posuere cubilia', 'Goldberg');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (21, 'scelerisque quam turpis adipiscing', 'Sirman');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (16, 'erat vestibulum sed magna at nunc commodo placerat', 'Davioud');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (35, 'erat', 'Cabane');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (14, 'morbi non lectus aliquam sit', 'Stanyland');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (21, 'ultrices posuere cubilia curae donec pharetra', 'Eastridge');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (16, 'pellentesque at nulla suspendisse potenti cras', 'Float');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (19, 'semper sapien a libero nam dui proin leo', 'Kippins');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (28, 'donec posuere metus vitae', 'Mattessen');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (14, 'lectus pellentesque at nulla suspendisse potenti cras', 'Foote');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (7, 'dis parturient montes nascetur ridiculus mus vivamus', 'Riddles');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (2, 'interdum mauris non', 'Gasken');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (31, 'risus dapibus augue vel accumsan tellus', 'Trousdale');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (26, 'volutpat', 'Stroder');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (1, 'aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien', 'Slarke');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (34, 'sem', 'McCalister');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (8, 'at ipsum ac tellus semper interdum mauris', 'Duggon');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (29, 'praesent blandit nam nulla integer', 'Jedrzejczak');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (25, 'tincidunt eu felis fusce posuere felis sed', 'Struijs');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (24, 'porttitor pede justo eu massa donec dapibus duis at velit', 'Dorrian');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (18, 'in faucibus orci luctus et ultrices posuere cubilia', 'Dunnan');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (9, 'sit amet', 'Afonso');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (23, 'aenean fermentum', 'Drabble');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (17, 'ipsum dolor sit amet consectetuer', 'Yurenev');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (10, 'vehicula condimentum', 'Gartshore');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (19, 'hac habitasse platea dictumst etiam', 'Pettegree');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (1, 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc', 'Lamblot');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (33, 'quis justo maecenas rhoncus aliquam lacus morbi quis', 'Windeatt');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (29, 'amet consectetuer adipiscing elit proin interdum mauris non', 'Sturdgess');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (16, 'vehicula condimentum', 'Linsey');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (3, 'amet eros suspendisse accumsan tortor quis', 'Foxon');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (33, 'at lorem integer tincidunt ante vel ipsum praesent', 'Cocker');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (7, 'nisi nam ultrices libero non mattis pulvinar nulla pede', 'Sline');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (4, 'platea dictumst maecenas ut massa quis augue luctus', 'Dinnage');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (26, 'sed magna', 'Frango');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (20, 'curabitur', 'Waiting');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (1, 'vulputate vitae nisl aenean lectus pellentesque eget', 'Lethby');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (27, 'lacinia erat vestibulum sed magna at nunc', 'Keddey');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (11, 'eget tempus vel', 'Baldwin');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (3, 'amet erat nulla tempus', 'Verni');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (14, 'odio curabitur convallis', 'Wakefield');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (15, 'consequat metus sapien ut nunc', 'Meany');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (31, 'odio in hac habitasse platea dictumst maecenas ut', 'Martinson');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (2, 'nam tristique tortor eu pede', 'Pothergill');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (19, 'neque', 'Keld');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (16, 'iaculis congue vivamus metus arcu adipiscing molestie hendrerit at', 'Macrow');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (35, 'id ligula suspendisse ornare consequat lectus in est risus', 'Mc Meekin');
INSERT INTO History (BuyerID, Searches, ProductsViewed) VALUES (38, 'ante vivamus tortor duis mattis egestas metus aenean', 'Gallone');