INSERT INTO ProductTags (ProductTagID, title) VALUES (1, 'Bags');
INSERT INTO ProductTags (ProductTagID, title) VALUES (2, 'Bags');
INSERT INTO ProductTags (ProductTagID, title) VALUES (3, 'Jewelry');
INSERT INTO ProductTags (ProductTagID, title) VALUES (4, 'Furniture');
INSERT INTO ProductTags (ProductTagID, title) VALUES (5, 'Food');
INSERT INTO ProductTags (ProductTagID, title) VALUES (6, 'Furniture');
INSERT INTO ProductTags (ProductTagID, title) VALUES (7, 'Shoes');
INSERT INTO ProductTags (ProductTagID, title) VALUES (8, 'Garden');
INSERT INTO ProductTags (ProductTagID, title) VALUES (9, 'Art');
INSERT INTO ProductTags (ProductTagID, title) VALUES (10, 'Furniture');
INSERT INTO ProductTags (ProductTagID, title) VALUES (11, 'Toys');
INSERT INTO ProductTags (ProductTagID, title) VALUES (12, 'Tools');
INSERT INTO ProductTags (ProductTagID, title) VALUES (13, 'Home Decor');
INSERT INTO ProductTags (ProductTagID, title) VALUES (14, 'Beauty');
INSERT INTO ProductTags (ProductTagID, title) VALUES (15, 'Pet Supplies');
INSERT INTO ProductTags (ProductTagID, title) VALUES (16, 'Pet Supplies');
INSERT INTO ProductTags (ProductTagID, title) VALUES (17, 'Clothing');
INSERT INTO ProductTags (ProductTagID, title) VALUES (18, 'Home Decor');
INSERT INTO ProductTags (ProductTagID, title) VALUES (19, 'Art');
INSERT INTO ProductTags (ProductTagID, title) VALUES (20, 'Garden');
INSERT INTO ProductTags (ProductTagID, title) VALUES (21, 'Jewelry');
INSERT INTO ProductTags (ProductTagID, title) VALUES (22, 'Music');
INSERT INTO ProductTags (ProductTagID, title) VALUES (23, 'Tools');
INSERT INTO ProductTags (ProductTagID, title) VALUES (24, 'Clothing');
INSERT INTO ProductTags (ProductTagID, title) VALUES (25, 'Electronics');
